version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/BackendConfiguration.Pn/BackendConfiguration.Pn.Test"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/BackendConfiguration.Pn/BackendConfiguration.Pn.Integration.Test"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/BackendConfiguration.Pn/BackendConfiguration.Pn"
  schedule:
    interval: daily
